### PR TITLE
Infrastructure rework

### PR DESCRIPTION
**Pull request by thogil**
Sync forks.

### CODE REVIEW

**Comment by shaunarundell** [comment]
Tom

Is this the merge of your fork back into the base ?

shaun

**Comment by LukePulverenti** [comment]
Shaun - the code is in a media browser repo but it's still the infrastructure rework branch. But it's getting close to matching the original feature set.

**Comment by shaunarundell** [comment]
is it workwhile blowing away the default branch and making your branch the
default.
Also, can you put a plan together for when you are going to formally
release the work you have done, make it the default so the communicaty can
get back to working on the MBT
please be honest and releastic if any further work required

shaun

**Comment by LukePulverenti** [comment]
of course there's a lot of work, but what's there is stable and superior to the current version. we've talked about floating it in the community while keeping the current one still active, so we may do that sooner rather than later.

**Comment by shaunarundell** [comment]
we just need to get to a stable single base.
no one is going to do any real work until we have a unified platform.

**Pull request merged**
